/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromiseTrackerRouteImport } from './routes/promise-tracker'
import { Route as PromiseTrackerIndexRouteImport } from './routes/promise-tracker.index'
import { Route as PromiseTrackerAllRouteImport } from './routes/promise-tracker.all'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromiseTrackerRoute = PromiseTrackerRouteImport.update({
  id: '/promise-tracker',
  path: '/promise-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const PromiseTrackerIndexRoute = PromiseTrackerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PromiseTrackerRoute,
} as any)
const PromiseTrackerAllRoute = PromiseTrackerAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => PromiseTrackerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/promise-tracker': typeof PromiseTrackerRouteWithChildren
  '/promise-tracker/all': typeof PromiseTrackerAllRoute
  '/promise-tracker/': typeof PromiseTrackerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/promise-tracker/all': typeof PromiseTrackerAllRoute
  '/promise-tracker': typeof PromiseTrackerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/promise-tracker': typeof PromiseTrackerRouteWithChildren
  '/promise-tracker/all': typeof PromiseTrackerAllRoute
  '/promise-tracker/': typeof PromiseTrackerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/promise-tracker' | '/promise-tracker/all' | '/promise-tracker/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/promise-tracker/all' | '/promise-tracker'
  id:
    | '__root__'
    | '/'
    | '/promise-tracker'
    | '/promise-tracker/all'
    | '/promise-tracker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromiseTrackerRoute: typeof PromiseTrackerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promise-tracker': {
      id: '/promise-tracker'
      path: '/promise-tracker'
      fullPath: '/promise-tracker'
      preLoaderRoute: typeof PromiseTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promise-tracker/': {
      id: '/promise-tracker/'
      path: '/'
      fullPath: '/promise-tracker/'
      preLoaderRoute: typeof PromiseTrackerIndexRouteImport
      parentRoute: typeof PromiseTrackerRoute
    }
    '/promise-tracker/all': {
      id: '/promise-tracker/all'
      path: '/all'
      fullPath: '/promise-tracker/all'
      preLoaderRoute: typeof PromiseTrackerAllRouteImport
      parentRoute: typeof PromiseTrackerRoute
    }
  }
}

interface PromiseTrackerRouteChildren {
  PromiseTrackerAllRoute: typeof PromiseTrackerAllRoute
  PromiseTrackerIndexRoute: typeof PromiseTrackerIndexRoute
}

const PromiseTrackerRouteChildren: PromiseTrackerRouteChildren = {
  PromiseTrackerAllRoute: PromiseTrackerAllRoute,
  PromiseTrackerIndexRoute: PromiseTrackerIndexRoute,
}

const PromiseTrackerRouteWithChildren = PromiseTrackerRoute._addFileChildren(
  PromiseTrackerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromiseTrackerRoute: PromiseTrackerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
